# Generated by Django 4.2 on 2023-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_rename_playlist_url_playlist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status_code',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
